// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://txnnvwxipmiuvvbsxwcr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4bm52d3hpcG1pdXZ2YnN4d2NyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg2ODkzNjksImV4cCI6MjA1NDI2NTM2OX0.Op0rQhXE9O6-axEzud1QZx-ogjKqqXy8EPvUAlMI5TA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);